version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/omni-meet-api
#file_exists_behaviour: OVERWRITE
hooks:
  ApplicationStart:
    - location: startup.sh
      timeout: 300
      runas: root
